### ISSUE TITLE
Floating point encoding of NaN and ±∞

### ISSUE THREAD

**Issue by jlouis** [cognitect/transit-format#20]
The IEEE 754 standard defines values for corner-case values:

    jlouis@eldar:~/P/plan9/lib$ ocaml
        OCaml version 4.01.0

    # 1.0 /. 0.0;;
    - : float = infinity
    # -1.0 /. 0.0;;
    - : float = neg_infinity
    # 0.0 /. 0.0;;
    - : float = nan
    # 

JSON, however, does not allow these to be represented. How will the format marshal these? I *expect* we use a ~d tag as in `"~dNaN"` and so on, but it would be nice to make this explicit.

**Comment by dchelimsky** [comment]
The "z" tag for special numbers was added to the spec: https://github.com/cognitect/transit-format#ground-and-extension-types for reference.
