### ISSUE TITLE
maps_*_char_sym_keys.json examples actually uses keywords and not symbols.

### ISSUE THREAD

**Issue by delaneyj** [cognitect/transit-format#27]
The contents of maps_two_char_sym_keys.json for example is: 
```[["^ ","~:aa",1,"~:bb",2],["^ ","^0",3,"^1",4],["^ ","^0",5,"^1",6]]```

When it should be:
```[["^ ","~$aa",1,"~$bb",2],["^ ","^0",3,"^1",4],["^ ","^0",5,"^1",6]]```

Can someone please confirm or rename / add a symbols example.

**Comment by delaneyj** [comment]
I saw the branch commit, all my tests (matching 1:1 with *.json examples) now work.  Thanks for the speedy response!

**Comment by dchelimsky** [comment]
Great. Merged to master.
